### ISSUE TITLE
NodeUp: A Very Meta NodeUp

### ISSUE THREAD

**Issue by dshaw** [nodeup/contribute#18]
### [NodeUp #53](http://nodeup.com/fiftythree)

With:
- @dshaw
- @khalifenizar
- ??
- ??

Topics:
- Discuss the impact of NodeUp on the Node community.
- Favorite shows and topics.
- What do you think about new concept shows like NodeUp Teams.
### Would you like to join us?

Tell us a little about yourself and what you'd like to share by posting a comment below?

**Comment by Nevraeka** [comment]
I'm a UX Engineer at 3Pillar Global. My current work is focused on rapidly prototyping applications we are working on for clients before the actual sprints start. Mainly I'm using Node on the backend with Express since I my code is ultimately throw away and used primarily as a interactive road map for devs before work starts.  One awesome thing about prototyping is I get to choose my target browsers and technology stack. I 've been using Rails and Front End MVC's mostly for the last 3 years but now that I'm at 3Pillar I get to use Node daily if I want to. 

I've been listening to NodeUp since episode 4. I love the discussions because they dive way deeper than simple tutorials plus I get to know who is innovating in this space & what projects I should learn from. I get to learn the latest and greatest ways to do what I need to do in Node. Since I'm teaching myself and fairly new it's so helpful to hear what more seasoned programmers are doing.

**Comment by tbuchok** [comment]
I am a programmer living in New York City, with a background in advertising tech where JavaScript is implemented in all the ways we love/complain about — ummm, `document.write` ... :\

In large part, NodeUp's focus on community -- heck, every show ends with an events wrap-up -- has led me to get really excited to talk about Node myself. I've given talks in Madrid, Croatia and here in NYC, so far. It's not only fun to talk about Node, but also to listen: episodes 19 ("An our favorite modules" and 41 ("A leveldb show") were particularly great.

I'd love to provide insight into one of my favorite themes with NodeUp -- what I call the `callback`. Often, I'm listening thinking, _How is the hell is this relevant?!_ and then a few weeks or months later -- I see the light! The subject matter gets, well, called-back. This happens enough that NodeUp positions itself as a great way to continue evolving as a Node developer -- NodeUp covers and seeds us with the ideas early and often.

This is complimented well with the concept shows -- particularly NodeUp Teams. One of NodeUp's strong benefits is how close the show is to `node-core` and prolific members of userland -- but hearing about additional use cases -- what are other businesses doing with Node, and how? -- rounds out the content from philosophical-to-practical wonderfully.

**Comment by cliffano** [comment]
I'm a software developer from Melbourne, Australia. I've been listening to NodeUp since the first episode, I documented 'Facts about Australia according to NodeUp' http://blog.cliffano.com/2012/03/23/australia-according-to-nodeup/ .
I've been using node since v0.2 days, back when promise was in core. I've abused npm by publishing Java code into npm registry, and vice versa. My most recent use of node is on a project with micro-services architecture where each service/app is a node module (that does one thing and does it well).

For me, NodeUp has been about learning from others:
- not too many projects out there which core developers talk regularly on podcasts
- I also enjoy the episodes where various prolific module authors discuss their differing opinions on certain topics (e.g. keeping X in node core vs in userland)
  Suggestion: How about a Node Smackdown as a concept show? e.g. this approach vs that approach, this framework vs that framework
- Melbourne/Australia is quite isolated from the rest of the world, so it's great to listen to those episodes covering various conferences in Europe and the US
- many of us use lots of technologies besides node, it's certainly impossible to do a deep dive on all of them just from reading. NodeUp has been great at providing detailed discussions on various interesting node topics.
  Suggestion: to get even more topics covered, perhaps have a NodeUpx ? a la TED and TEDx
  I wonder how non-English speaking node communities are going with deep dive discussions like the ones that NodeUp provides.

The podcast format is great too:
- Melbourne trains get real crowded during peak hours and I have to stand up squashed like a sardine, the only useful thing to do is to listen to tech podcasts

NodeUp Teams concept is great. +1
Learning from other teams' wins and battle scars will make more dev teams around the world better. "Great dev teams make other dev teams better." - Codefucius

**Comment by mattcreager** [comment]
In lots of ways NodeUp is responsible for where I'm currently working, what I'm working on and who I'm doing it with.  That's heavy, but it's true:

I'm a member of the software engineering team at [GoInstant](https://goinstant.com/) and live and work in [Halifax, NS](https://maps.google.ca/maps?q=halifax+regional+municipality&ie=UTF-8&hq=&hnear=0x4b4513bbd026ebc5:0x1b0497d93c43b220,Halifax,+NS&gl=ca&ei=QIxlUpzROsfb4AOX74DIDg&ved=0CL8BELYD) we're trying to make it stupid easy to build realtime, multi-user apps.

Before GoInstant I was with BlackBerry... yes, I dodged that bullet *phew.  I stumbled across NodeUp, while building a real-time data analytics dashboard and googling around for the most effective, scalable way to accomplish the task at hand. I landed on the NodeUp website and so began a marathon of every available episode.

I couldn't convince my leadership that NodeJS was a production ready solution at BlackBerry (that was a point of great consternation at the time), so I began using it in my own projects, until to my complete surprise (I was convinced I was the only one using Node in Halifax) a local Node hackathon was [announced](https://goinstant.com/blog/come-to-the-2nd-goinstant-nodejs-hackathon).  After which, I spent hours just discussing Node & NodeUp with the same great team I'm now working with.

I agree with the comments above, NodeUp is at the center of the community, partially because of how valuable it is to those within the community:

The deep dive episodes actually make me immediately more effective so those are my favorite. It's easy to figure out which libraries are popular, but NodeUp helps me understand:
-  Why a particular part of the community is winning the race with their module
-  Why it matters to me and 
-  How I can take advantage of it

NodeUp almost exposes me to concepts I either find too intimidating to research (binary compatibility anyone?) or just hadn't considered a possible application for node (nodebots ftw) which is a really critical part of personal growth, which in turn is really important to community growth.
