### ISSUE TITLE
NodeUp: A libuv Show

### ISSUE THREAD

**Issue by jugglinmike** [nodeup/contribute#34]
libuv receives regular mention on NodeUp, but it's never been discussed in-depth. It would be good to hear about the library's responsibilities generally (outside of Node), how it integrates with Node, and other projects that depend on it.

**Comment by dshaw** [comment]
:+1:

**Comment by FredKSchott** [comment]
:+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by Qard** [comment]
:+1:

**Comment by rvagg** [comment]
I'd love to do this show, would coincide well with libuv movind to its own org.  Can we collect some names of people on this? @saghul do you want to name 3 - 4 people that are involved in development or heavy downstream use of libuv that would provide interesting perspective on the project as distinct from Node (although people obviously want to hear about Node in this too). 

/cc @indutny  @piscisaureus @bnoordhuis

**Comment by saghul** [comment]
Hi Rod!

I myself am a libuv downstream (I wrote pyuv, which is what ultimately got me into libuv, not node). Tim (@creationix) has done a lot of work with Lua, I'm not sure who to name, but getting someone from Julia would be cool too. Microsoft recently released Kestrel (https://github.com/aspnet/KestrelHttpServer), it would be great to have someone tell us about it.

**Comment by creationix** [comment]
Sorry if this is too much information for this thread, but I thought I'd share how I've been using libuv outside of node.js for the past few years.

I wrote three different libuv bindings for lua (the latest being what's current in the luvit/luv repo).  I also started bindings for @indutny's candor language https://github.com/creationix/candor.io and recently started on bindings for duktape https://github.com/creationix/dukluv.  A while back I started on spidermonkey bindings https://github.com/creationix/luvmonkey but got stuck because of lack of accurate sm docs.  All the bindings except the new version of luv are against libuv 0.8.x.  The new luv is against libuv 1.0.0.

My past two lua bindings are being used on production at various places.  The bindings in legacy luvit are in production at rackspace with thousands of servers.  The older luv bindings are used in the popular Torch7 framework (http://torch.ch/).

**Comment by creationix** [comment]
I believe @brianleroux started on libuv bindings for JSC (JavaScriptCore) which I find very interesting and wanted to do myself, but never had time for some odd reason.

**Comment by piscisaureus** [comment]
I'd be happy to join you there.

**Comment by floating** [comment]
http://nodeup.com/eightythree

**Comment by jugglinmike** [comment]
Thanks, Nodeup--I'm really looking forward to this one :)
