### ISSUE TITLE
NodeUp: A Socket.IO 1.0 show

### ISSUE THREAD

**Issue by toblerpwn** [nodeup/contribute#37]
### [NodeUp #64](http://nodeup.com/sixtyfour)

With:
- @dshaw
- @guille
- @secoif 

Topics:
- Socket.io 1.0
  - http://socket.io/
  - https://github.com/Automattic/socket.io

Original post from @toblerpwn:

> been a year since your last web sockets show (which I just listened to, and it was GREAT!). is socket.io still the standard? how does 1.0 scale in prod? stores are a thing of the past - what are connectors (I think that's what they're called now anyway!) and how do they work with multi-box/multi-process node implementations? how did engine.io turn out as a standalone package? should users on a stable fork of 0.9.x migrate to 1.0? if not, why not? sockets are what brought a lot of us to node; would be great to get another episode about the current state of things :)

**Comment by dshaw** [comment]
@rauchg @3rd-Eden Anyone who we should pull in for this show?

**Comment by rosskukulinski** [comment]
I'd also be curious to hear more about [Primus](https://github.com/primus/primus/) which seems to be gaining traction.

**Comment by 3rd-Eden** [comment]
@dshaw you probably meant to mention @guille, damned confusing twitter/github handles ;-p

And I didn't do much on Socket.IO 1.0, I've only been fixing bugs in Engine.IO that got reported through Primus. So for pure Socket.IO 1.0 show, i'll probably be a bit useless.

**Comment by nizaroni** [comment]
I think it would be far more interesting to focus on the state of WebSocket abstractions as a whole, but that may be too large a scope for a single show.

That said, I know almost nothing about Socket.IO 1.0 so a show about that would be valuable to me as well.

**Comment by dshaw** [comment]
Totally agree @khalifenizar.

Thanks, @3rd-Eden (I double checked yours before posting :smile:.)

**Comment by objectiveSee** [comment]
+1 

Would love to hear about the new redis-store, or whatever Socket.io 1.0 is using.

**Comment by rauchg** [comment]
+1

On Thu, Apr 17, 2014 at 11:48 AM, objectiveSee notifications@github.comwrote:

> +1
> 
> Would love to hear about the new redis-store, or whatever Socket.io 1.0 is
> using.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/37#issuecomment-40748769
> .

## 

Guillermo Rauch (@rauchg https://twitter.com/rauchg)

**Comment by DamonOehlman** [comment]
I don't think it should be a pure Socket.IO show as I imagine a few people (such as myself) have moved across to using primus instead of Socket.IO.  I certainly think it would be useful for @3rd-Eden to get involved and to have a discussion around "when is a good time to use Socket.IO and when is a good time to use Primus" (it may just be that it's a matter of personal preference).  And maybe even look at whether it makes sense to look at a unification effort sometime in the future.

Additionally, while probably best left to a whole other show I think @guille would probably have a lot of interesting things to say on the topic of "Help open-source maintainers stay sane" : isaacs/github#167

**Comment by dshaw** [comment]
@DamonOehlman That ship has sailed. Also, there is not a finite number of NodeUps. Please feel free to propose new show(s).

**Comment by DamonOehlman** [comment]
@dshaw I should pay more attention, and yes will do.

**Comment by dshaw** [comment]
Show should be soon!
